"""add reconstruction metadata table

Revision ID: 2f1537708f20
Revises: acef06dab9a4
Create Date: 2026-09-17 16:03:46.964227

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1537708f20'
down_revision: Union[str, None] = 'acef06dab9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconstruction_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconstruction_job_id', sa.Integer(), nullable=False),
    sa.Column('feature_detector', sa.String(), nullable=True),
    sa.Column('matcher_type', sa.String(), nullable=True),
    sa.Column('depth_method', sa.String(), nullable=True),
    sa.Column('input_frame_count', sa.Integer(), nullable=True),
    sa.Column('input_resolution', sa.String(), nullable=True),
    sa.Column('input_duration_seconds', sa.Float(), nullable=True),
    sa.Column('features_detected', sa.Integer(), nullable=True),
    sa.Column('features_matched', sa.Integer(), nullable=True),
    sa.Column('inlier_ratio', sa.Float(), nullable=True),
    sa.Column('camera_poses_estimated', sa.Integer(), nullable=True),
    sa.Column('mean_reprojection_error', sa.Float(), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('point_density', sa.Float(), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('mesh_volume', sa.Float(), nullable=True),
    sa.Column('mesh_surface_area', sa.Float(), nullable=True),
    sa.Column('texture_resolution', sa.String(), nullable=True),
    sa.Column('texture_quality_score', sa.Float(), nullable=True),
    sa.Column('overall_quality', sa.String(), nullable=True),
    sa.Column('alignment_confidence', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('feature_detection_time', sa.Float(), nullable=True),
    sa.Column('matching_time', sa.Float(), nullable=True),
    sa.Column('sfm_time', sa.Float(), nullable=True),
    sa.Column('mesh_generation_time', sa.Float(), nullable=True),
    sa.Column('texture_time', sa.Float(), nullable=True),
    sa.Column('optimization_time', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reconstruction_job_id'], ['reconstruction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconstruction_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconstruction_metadata_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstruction_metadata_reconstruction_job_id'), ['reconstruction_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconstruction_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconstruction_metadata_reconstruction_job_id'))
        batch_op.drop_index(batch_op.f('ix_reconstruction_metadata_id'))

    op.drop_table('reconstruction_metadata')
    # ### end Alembic commands ###
