"""add upload jobs and permissions tables

Revision ID: 2ec5b3d95e34
Revises: 8c29f72e6404
Create Date: 2026-09-17 12:52:16.487783

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec5b3d95e34'
down_revision: Union[str, None] = '8c29f72e6404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
