"""initial schema

Revision ID: 8c29f72e6404
Revises: 
Create Date: 2026-09-17 09:51:30.209077

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c29f72e6404'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('required_value', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_achievement_id'), ['achievement_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievements_id'), ['id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.String(), nullable=False),
    sa.Column('required_action', sa.String(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_quest_id'), ['quest_id'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location_sharing', sa.Boolean(), nullable=True),
    sa.Column('approximate_location', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('model_3d_path', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('device_orientation', sa.Float(), nullable=True),
    sa.Column('video_resolution', sa.String(), nullable=True),
    sa.Column('video_fps', sa.Float(), nullable=True),
    sa.Column('capture_duration', sa.Float(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('alignment_confidence', sa.Float(), nullable=True),
    sa.Column('alignment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_id'), ['id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('player_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_achievements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('player_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locations_discovered', sa.Integer(), nullable=True),
    sa.Column('total_distance_traveled', sa.Float(), nullable=True),
    sa.Column('time_played_seconds', sa.Integer(), nullable=True),
    sa.Column('locations_collected', sa.Integer(), nullable=True),
    sa.Column('items_collected', sa.Integer(), nullable=True),
    sa.Column('friends_count', sa.Integer(), nullable=True),
    sa.Column('locations_created', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_progress_user_id'), ['user_id'], unique=True)

    op.create_table('player_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_quests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_quests_quest_id'), ['quest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_quests_user_id'), ['user_id'], unique=False)

    op.create_table('game_worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('map_data', sa.Text(), nullable=True),
    sa.Column('spawn_x', sa.Float(), nullable=True),
    sa.Column('spawn_y', sa.Float(), nullable=True),
    sa.Column('spawn_z', sa.Float(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_worlds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_worlds_id'), ['id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('grid_cell_id', sa.String(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('bbox_min_x', sa.Float(), nullable=True),
    sa.Column('bbox_min_y', sa.Float(), nullable=True),
    sa.Column('bbox_min_z', sa.Float(), nullable=True),
    sa.Column('bbox_max_x', sa.Float(), nullable=True),
    sa.Column('bbox_max_y', sa.Float(), nullable=True),
    sa.Column('bbox_max_z', sa.Float(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.String(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alignment_method', sa.String(), nullable=True),
    sa.Column('reconstruction_quality', sa.String(), nullable=True),
    sa.Column('geometry_provenance', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('moderation_state', sa.String(), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_grid_cell_id'), ['grid_cell_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('reconstruction_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('result_asset_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconstruction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconstruction_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstruction_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reconstruction_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('collected_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collected_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collected_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_locations_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_locations_user_id'), ['user_id'], unique=False)

    op.create_table('discovered_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_locations_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_locations_user_id'), ['user_id'], unique=False)

    op.create_table('location_categories',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'category_id')
    )
    op.create_table('location_tags',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_tags')
    op.drop_table('location_categories')
    with op.batch_alter_table('discovered_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_locations_location_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_locations_id'))

    op.drop_table('discovered_locations')
    with op.batch_alter_table('collected_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collected_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_collected_locations_location_id'))
        batch_op.drop_index(batch_op.f('ix_collected_locations_id'))

    op.drop_table('collected_locations')
    with op.batch_alter_table('reconstruction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconstruction_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_reconstruction_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_reconstruction_jobs_id'))

    op.drop_table('reconstruction_jobs')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))
        batch_op.drop_index(batch_op.f('ix_locations_grid_cell_id'))

    op.drop_table('locations')
    with op.batch_alter_table('game_worlds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_worlds_id'))

    op.drop_table('game_worlds')
    with op.batch_alter_table('player_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_quests_user_id'))
        batch_op.drop_index(batch_op.f('ix_player_quests_quest_id'))
        batch_op.drop_index(batch_op.f('ix_player_quests_id'))

    op.drop_table('player_quests')
    with op.batch_alter_table('player_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_player_progress_id'))

    op.drop_table('player_progress')
    with op.batch_alter_table('player_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_player_achievements_id'))
        batch_op.drop_index(batch_op.f('ix_player_achievements_achievement_id'))

    op.drop_table('player_achievements')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_id'))

    op.drop_table('captures')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_quest_id'))
        batch_op.drop_index(batch_op.f('ix_quests_id'))

    op.drop_table('quests')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_achievement_id'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
