"""add visual landmarks and matches tables

Revision ID: d88dc0fefdae
Revises: 2f1537708f20
Create Date: 2026-09-17 16:18:16.115291

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88dc0fefdae'
down_revision: Union[str, None] = '2f1537708f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('descriptor_count', sa.Integer(), nullable=True),
    sa.Column('descriptor_data', sa.LargeBinary(), nullable=True),
    sa.Column('keypoint_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('uniqueness_score', sa.Float(), nullable=True),
    sa.Column('visibility_range', sa.Float(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('capture_conditions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_landmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_landmarks_capture_id'), ['capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_landmarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_landmarks_image_hash'), ['image_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_landmarks_location_id'), ['location_id'], unique=False)

    op.create_table('landmark_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_capture_id', sa.Integer(), nullable=True),
    sa.Column('query_image_hash', sa.String(), nullable=True),
    sa.Column('matched_landmark_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_distance', sa.Float(), nullable=True),
    sa.Column('inlier_count', sa.Integer(), nullable=True),
    sa.Column('outlier_ratio', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['matched_landmark_id'], ['visual_landmarks.id'], ),
    sa.ForeignKeyConstraint(['query_capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landmark_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landmark_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_landmark_matches_matched_landmark_id'), ['matched_landmark_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_landmark_matches_query_capture_id'), ['query_capture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landmark_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landmark_matches_query_capture_id'))
        batch_op.drop_index(batch_op.f('ix_landmark_matches_matched_landmark_id'))
        batch_op.drop_index(batch_op.f('ix_landmark_matches_id'))

    op.drop_table('landmark_matches')
    with op.batch_alter_table('visual_landmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_landmarks_location_id'))
        batch_op.drop_index(batch_op.f('ix_visual_landmarks_image_hash'))
        batch_op.drop_index(batch_op.f('ix_visual_landmarks_id'))
        batch_op.drop_index(batch_op.f('ix_visual_landmarks_capture_id'))

    op.drop_table('visual_landmarks')
    # ### end Alembic commands ###
