"""add events and virtual meetups tables

Revision ID: 312a58d62f4e
Revises: 2ec5b3d95e34
Create Date: 2026-09-17 15:39:52.669285

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312a58d62f4e'
down_revision: Union[str, None] = '2ec5b3d95e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_game_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_location_id'), ['location_id'], unique=False)

    op.create_table('virtual_meetups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_meetups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_meetups_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_meetups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_meetups_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_meetups_meetup_id'), ['meetup_id'], unique=True)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['game_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_user_id'), ['user_id'], unique=False)

    op.create_table('meetup_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], ['virtual_meetups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetup_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetup_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetup_participants_meetup_id'), ['meetup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetup_participants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetup_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetup_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_meetup_participants_meetup_id'))
        batch_op.drop_index(batch_op.f('ix_meetup_participants_id'))

    op.drop_table('meetup_participants')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))

    op.drop_table('event_participants')
    with op.batch_alter_table('virtual_meetups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_meetups_meetup_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_meetups_location_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_meetups_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_meetups_host_id'))

    op.drop_table('virtual_meetups')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_events_location_id'))
        batch_op.drop_index(batch_op.f('ix_game_events_id'))
        batch_op.drop_index(batch_op.f('ix_game_events_event_id'))

    op.drop_table('game_events')
    # ### end Alembic commands ###
